In [1]:
import sklearn
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn import svm,datasets
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("result_002.csv")

In [3]:
df=df.drop(columns=['30','31','32','33','34','35','36'])

In [4]:
scaler=MinMaxScaler()
for i in range(0,30):
    scaler.fit(df[['{}'.format(i)]])
    df[['{}'.format(i)]]=scaler.transform(df[['{}'.format(i)]])

In [5]:
data=df.drop(columns=['rate','p','n'])

In [6]:
target_p=df[['p']]
target_n=df[['n']]
target_rate=df[['rate']]

In [13]:
tar=[]
all_f1score=[]
for i in [target_p,target_n,target_rate]:
    x_train, x_test, y_train, y_test = train_test_split(data, i, test_size=0.2,shuffle=False , random_state=42)
    #model=svm.SVC(kernel='linear')
    model=RidgeClassifier()
    model.fit(x_train,np.array(y_train).ravel())
    pred=model.predict(x_test)
    tar.append(pred)
    all_pred=np.stack(tuple(tar))
    
    fscore=f1_score(y_test, pred, average='weighted')
    all_f1score.append(fscore)
print(all_pred, "p, n ,rate \n\n",all_f1score,"p, n ,rate")

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] p, n ,rate 

 [0.7402952344077904, 0.7414976052397728, 0.504510069346545] p, n ,rate
